<?php

use Drupal\isueo_helpers\ISUEOHelpers\Wrappers;

/**
 * Implements hook_install().
 */
function isueo_card_deck_install()
{
  // Add a few permissions to Content Editor role
  $permissions = [
    'access block library',
    'delete any isueo_card_deck block content',
    'edit any isueo_card_deck block content',
  ];
  Wrappers::changeRolePermissions('content_editor', $permissions, TRUE);
}
