<?php

use Drupal\node\Entity\Node;
use Drupal\isueo_helpers\ISUEOHelpers;

//include_once('plp_courses.page.inc');

/**
 * Implements hook_rebuild().
 */
function plp_courses_rebuild()
{
  plp_courses_getcourses();
  //plp_typesense_index_all_courses();
}

/**
 * Implements hook_cron().
 */
function plp_courses_cron()
{
  plp_courses_getcourses();
}

function plp_courses_getcourses()
{

  //$feed_url = 'modules/custom/d8modules/program_landing_page/plp_courses/OnlineCourseOfferingExample.json';
  $feed_url = 'https://datastore.exnet.iastate.edu/mydata/ProductOfferings-Courses.json';
  // Get the courses feed, if it's empty, wait 1 second and try again
  $raw = ISUEOHelpers\Files::fetch_url($feed_url);
  if ($raw === false || strlen($raw) < 10000) {
    sleep(1);
    echo 'Sleeping...' . PHP_EOL;
    Drupal::logger('plp_courses')->info('Empty feed: wait 1 second and try again');
    $raw = ISUEOHelpers\Files::fetch_url($feed_url);
  }
  $courses = json_decode($raw, true);

  // Record type(s) for courses
  $types = ['012UO000002XNXlYAO'];

  //$config = Drupal::config('plp_courses.settings');

  /*
  $products = json_decode($raw, true);
  $courses = [];
  $children = [];
  $nodeIds = [];
  $min_courses = 100;
  if (!is_array($products) || count($products) < $min_courses) {
    Drupal::logger('plp_courses')->info('Less than ' . $min_courses . ' courses, exiting');
    return;
  }

  $events = plp_courses_get_related_items('https://datastore.exnet.iastate.edu/mydata/UpcomingProgramOfferings.json', 'Planned_Program__c', $courses);
  $measurements = plp_courses_get_related_items('https://datastore.exnet.iastate.edu/mydata/IndicatorMeasures.json', 'Planned_Program__c', $courses);
  $indicators = plp_courses_get_related_items('https://datastore.exnet.iastate.edu/mydata/EducationalcoursesIndicatorConnectors.json', 'Related_Extension_Product__c', $courses);
  $counties = plp_courses_get_related_items('https://datastore.exnet.iastate.edu/mydata/CountyEducationalcourses.json', 'mydataID', $courses);

  $intended_audiences = ISUEOHelpers\Taxonomy::get_terms('intended_audiences');
  $program_areas = ISUEOHelpers\Taxonomy::get_terms('program_areas');
  $critical_issues = ISUEOHelpers\Taxonomy::get_terms('critical_issues');
  $interest_areas = ISUEOHelpers\Taxonomy::get_terms('interest_areas');
  $categories_topics = ISUEOHelpers\Taxonomy::get_terms('categories_topics');
  */

  $programIds = [];
  // Get all existing program and child nodes
  $nodes = plp_courses_get_existing_nodes('plp_course', 'field_plp_course_mydata_id');
  $nodeIds = array_keys($nodes);

  echo 'Nodes: ' . count($nodeIds) . PHP_EOL;

  foreach ($courses as $course) {
    if (!in_array($course['RecordTypeId'], $types)) {
      continue;
    }

    // Only include courses for programs that are in the PLP
    $program_node = plp_courses_get_program_node($course);
    if ($program_node == null) {
      continue;
    }

    $programIds[] = $course['Id'];
    $mynode = null;
    $save = false;

    // Check for existing node, create one if needed
    if (!empty($nodes[$course['Id']])) {
      $mynode = $nodes[$course['Id']];
    } else {
      $mynode = Node::create(array('type' => 'plp_course', 'title' => html_entity_decode($course['Name']), 'field_plp_course_mydata_id' => $course['Id'],));
      $mynode->save();
      $save = true;
    }

    // Handle Title
    if ($mynode->getTitle() != html_entity_decode($course['Name'])) {
      $mynode->setTitle(html_entity_decode($course['Name']));
      $save = true;
    }

    // Handle Body
    //$body = plp_courses_generate_body($course);
    $body = $course['Offering_Description__c'];
    if ($mynode->body->value != $body) {
      $mynode->body->value = $body;
      $mynode->body->format = 'basic';
      $save = true;
    }

    if ($mynode->get('field_plp_course_program_id')->getString() != $program_node->get('field_plp_program_mydata_id')->getString()) {
      $mynode->set('field_plp_course_program_id', $program_node->get('field_plp_program_mydata_id')->getString());
      $save = true;
    }

    /*
    // Handle the text fields using an array and a loop
    $fields = [
      'field_plp_course_program_id' => 'hed__Course__c',
    ];
    foreach ($fields as $key => $value) {
      if ($mynode->get($key)->getString() != $course[$value]) {
        $mynode->set($key, $course[$value]);
        $save = true;
      }
    }
      */

    /* Insert lines here */

    // Only save if there has been a changed, this saves a ton of time
    if ($save) {
      $mynode->save();
    }
  }

  /*

  // Step through the courses feed
  foreach ($courses as $program) {

    if ($mynode->body->summary != $program['hed__Description__c']) {
      $mynode->body->summary = $program['hed__Description__c'];
      $save = true;
    }

    // Handle website link
    $website = empty($program['Planned_Program_Website__c']) ? '' : plp_courses_fix_url($program['Planned_Program_Website__c']);
    if ($mynode->get('field_plp_program_website')->uri != $website) {
      $mynode->set('field_plp_program_website', ['uri' => $website, 'title' => 'More about ' . $program['Name']]);
      $save = true;
    }

    // Handle taxonomy lookup fields
    $fields_single_entity_reference = [
      'field_plp_program_audiences' => ['taxonomy_array' => &$intended_audiences, 'taxonomy_id' => 'intended_audiences', 'json_element' => 'Intended_Audiences__c'],
      'field_plp_program_critical_issue' => ['taxonomy_array' => &$critical_issues, 'taxonomy_id' => 'critical_issues', 'json_element' => 'Critical_Issue__c'],
      'field_plp_program_interest_areas' => ['taxonomy_array' => &$interest_areas, 'taxonomy_id' => 'interest_areas', 'json_element' => 'Related_Interest_Areas__c'],
      'field_plp_program_program_area' => ['taxonomy_array' => &$program_areas, 'taxonomy_id' => 'program_areas', 'json_element' => 'hed__Account__r.Name'],
      'field_plp_program_category' => ['taxonomy_array' => &$categories_topics, 'taxonomy_id' => 'categories_topics', 'json_element' => 'Program_landing_Page_Category__c'],
      'field_plp_program_topics' => ['taxonomy_array' => &$categories_topics, 'taxonomy_id' => 'categories_topics', 'json_element' => 'Program_Landing_Page_Topic__c'],
    ];
    foreach ($fields_single_entity_reference as $key => $value) {
      $terms = [];
      if (!empty($program[$value['json_element']])) {
        foreach (explode(';', $program[$value['json_element']]) as $new_term) {
          $term_id = ISUEOHelpers\Taxonomy::get_term_id($new_term, $value['taxonomy_array'], $value['taxonomy_id']);
          $terms[] = $term_id;
        }
      }
      if ($mynode->get($key)->getString() != implode(', ', $terms)) {
        $mynode->set($key, $terms);
        $save = true;
      }
    }

    // Handle number fields
    $number_fields = [
      'field_plp_program_num_events' => $events,
      'field_plp_program_num_indicators' => $indicators,
      'field_plp_program_num_measures' => $measurements,
    ];
    foreach ($number_fields as $key => $value) {
      $num = plp_courses_get_number_of_items($program['Id'], $value, $children);
      if ($mynode->get($key)->getString() != $num) {
        $mynode->set($key, $num);
        $save = true;
      }
    }

    // Get list of programID's that should be include in event list
    $event_courses = [$program['Id']];
    if (array_key_exists($program['Id'], $children)) {
      ksort($children[$program['Id']]);
      foreach ($children[$program['Id']] as $child) {
        $event_courses[] = $child['Id'];
      }
    }
    $tmpstring = serialize($event_courses);
    if ($mynode->field_plp_program_event_pgm_ids->value != $tmpstring) {
      $mynode->set('field_plp_program_event_pgm_ids', $tmpstring);
      $save = true;
    }

    // Handle counties, use the same list of courses as events
    $tmpstring = plp_courses_get_counties($counties, $event_courses);
    if ($mynode->field_plp_program_on_counties->value != $tmpstring) {
      $mynode->set('field_plp_program_on_counties', $tmpstring);
      $save = true;
    }

    // Handle when a program shouldn't have children
    if (!array_key_exists($program['Id'], $child_nodes) && !empty($mynode->field_plp_program_children[0])) {
      $mynode->set('field_plp_program_children', []);
      $save = true;
    }

    // Handle Program Children
    if (array_key_exists($program['Id'], $child_nodes)) {
      $tmp_existing_children = explode(', ', $mynode->field_plp_program_children->getString());
      sort($tmp_existing_children);
      $tmp_new_children = $child_nodes[$program['Id']];
      sort($tmp_new_children);

      if ($tmp_existing_children != $tmp_new_children) {
        $mynode->set('field_plp_program_children', $tmp_new_children);
        $save = true;
      }
    }

    // Calculate the sort number
    $tmpnum = plp_courses_sort_calculator($mynode, $child_nodes, $program['Id'], $config);
    if ($mynode->field_plp_program_sort_calc->value != $tmpnum) {
      $mynode->set('field_plp_program_sort_calc', $tmpnum);
      $save = true;
    }

    // Publish the node if it's unpublished
    if (!$mynode->isPublished()) {
      $mynode->setPublished();
      $save = true;
    }
  }

  // Find and unpublish deleted courses
  $nodes_to_unpublish = array_diff($nodeIds, $programIds);
  if (!empty($nodes_to_unpublish)) {
    $nids = Drupal::entityQuery('node')->accessCheck(false)->condition('type', 'plp_program')->condition('status', 1)->condition('field_plp_program_mydata_id', $nodes_to_unpublish, 'IN')->execute();

    $tmpnodes =  Node::loadMultiple($nids);
    foreach ($tmpnodes as $node) {
      $node->setUnpublished()->save();
    }
  }
  plp_courses_handle_topic_hierarchy($categories_topics, $courses);
  */
}

/**
 * Implements hook_preprocess_HOOK().
 */

function plp_courses_preprocess_page_title(&$variables)
{
  // Try to put the program name into the title on the events page
  $referring_node_id = intval(Drupal::request()->query->get('referring_nid'));
  $current_node = \Drupal::request()->attributes->get('node');

  if ($referring_node_id && $current_node && $current_node->bundle() == 'page') {
    $referring_node = Node::load($referring_node_id);
    if ($referring_node) {
      $variables['title'] = 'Events for "' . $referring_node->getTitle() . '"';
      $variables['#cache']['max-age'] = 0;
    }
  }
}

/**
 * Implements hook_theme().
 */

function plp_courses_theme($existing, $type, $theme, $path)
{
  return [
    'page__type__plp_program__canonical' => [
      'template' => 'page--type--plp-program--canonical',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */

function plp_courses_preprocess_node(&$variables)
{
  // Add the css file if we're on content type of plp_program
  $node = $variables['node'];
  if ($node->getType() == 'plp_program') {
    $variables['#attached']['library'][] = 'plp_courses/plp_courses';
  }
}

// Return an array of existing nodes with MyData ID as the array key
function plp_courses_get_existing_nodes(string $content_type, string $mydata_id_field)
{
  $nids = \Drupal::entityQuery('node')->accessCheck(false)->condition('type', $content_type)->execute();
  $tmpnodes =  Node::loadMultiple($nids);
  $nodes = [];
  foreach ($tmpnodes as $node) {
    $nodes[$node->get($mydata_id_field)->getString()] = $node;
  }

  return $nodes;
}

// Get the Mydata ID of the program for this course, this program must be a published Program in the PLP
function plp_courses_get_program_node($course)
{
  $program_node = null;
  $nids = \Drupal::entityQuery('node')
    ->accessCheck(false)
    ->condition('type', 'plp_program')
    ->condition('status', 1)
    ->condition('field_plp_program_event_pgm_ids', $course['hed__Course__c'], 'CONTAINS')
    ->execute();
  if (count($nids) == 1) {
    $program_node = Node::load(reset($nids));
  }

  return $program_node;
}
