<?php

/**
* Implements hook_theme().
*/

function ts_events_details_theme($existing, $type, $theme, $path) {
  return [
    'ts_events_details' => [
      'variables' => [
        'title' => '',
        'event' => [],
        'smugmug_id' => '',
        'date' => [],
        'online' => false,
        'address' => [],
        'description' => '',
        'contact' => [],
        'instructor' => [],
        'sessions' => [],
        'urls' => [],
        'registration' => [],
      ],
    ],
  ];
}
