<?php

/**
 * @file
 * Install functions for pubs_entity_from_feed module
 */

 /**
 * Implements hook_install().
 */

 function pubs_entity_from_feed_install() {
  $config = \Drupal::service('config.factory')->getEditable('pubs_entity_type.settings');
  $config->set('pubs_json_feed', 'https://eis-prod.its.iastate.edu/store/api/products/top');
  $config->save();

  pubs_entity_from_feed_rebuild();
 }
