<?php

use \Drupal\isueo_helpers\ISUEOHelpers\Typesense;

/**
 * Implements hook_ENTITY_TYPE_delete().
 */

function ts_forstaff_node_delete(Drupal\Core\Entity\EntityInterface $entity)
{
  try {
    $config = Drupal::config('ts_forstaff.settings');
    $client = Typesense::getClient($config->get('api_key'));

    $contentTypes = $config->get('content_types');

    if (in_array($entity->bundle(), $contentTypes)) {
      $client->collections[$config->get('collection')]->documents[$config->get('site_name') . ':' . $entity->id()]->delete();
    }
  } catch (Exception $e) {
    Drupal::logger('ts_forstaff')->error('Deleting a node from ForStaff Typesense Collection: ' . $e->getMessage());
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */

function ts_forstaff_node_update(Drupal\Core\Entity\EntityInterface $entity)
{
  $config = Drupal::config('ts_forstaff.settings');

  $contentTypes = $config->get('content_types');

  if (in_array($entity->bundle(), $contentTypes)) {
    if ($entity->isPublished()) {
      Typesense::index_node($entity, $config->get('api_key'), $config->get('collection'), $config->get('site_name'), $config->get('home_url'));
    } else {
      if ($entity->original->isPublished()) {
        ts_forstaff_node_delete($entity);
      }
    }
  }
}

function ts_forstaff_index_all_nodes()
{
  try {
    $config = Drupal::config('ts_forstaff.settings');
    $contentTypes = array_values($config->get('content_types'));

    ts_forstaff_delete_all_from_collection();

    foreach ($contentTypes as $type) {
      $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['type' => $type, 'status' => 1,]);
      foreach ($nodes as $node) {
        Typesense::index_node($node, $config->get('api_key'), $config->get('collection'), $config->get('site_name'), $config->get('home_url'));
      }
    }
  } catch (Exception $e) {
    Drupal::logger('ts_forstaff')->error('Indexing all nodes in ForStaff Typesense: ' . $e->getMessage());
  }
}

function ts_forstaff_delete_all_from_collection($sitename = '')
{
  $config = Drupal::config('ts_forstaff.settings');
  $client = Typesense::getClient($config->get('api_key'));
  $sitename = empty($sitename) ? $config->get('site_name') : $sitename;
  $client->collections[$config->get('collection')]->documents->delete(['filter_by' => 'site_name:=' . $sitename,]);
}
