<?php

/**
 * Implements hook_preprocess_HOOK()
 */
function program_offering_blocks_preprocess_block(&$variables)
{
  // Include the program_offering_blocks css file for the block
  if (substr($variables['plugin_id'], 0, 23) == 'program_offering_blocks') {
    $variables['#attached']['library'][] = 'program_offering_blocks/program_offering_blocks_block';
    $variables['attributes']['class'][] = 'program_offering_blocks';
  }
}

/**
* Implements hook_theme().
*/

function program_offering_blocks_theme($existing, $type, $theme, $path) {
  return [
    'program_offering_details_multisession' => [
      'variables' => [
        'title' => '',
        'smugmug_id' => '',
        'date' => [],
        'online' => false,
        'address' => [],
        'description' => '',
        'contact' => [],
        'instructor' => [],
        'sessions' => [],
        'urls' => [],
        'registration' => [],
      ],
    ],
    'program_offering_details_singlesession' => [
      'variables' => [
        'title' => '',
        'smugmug_id' => '',
        'date' => [],
        'online' => false,
        'address' => [],
        'description' => '',
        'contact' => [],
        'instructor' => [],
        'sessions' => [],
        'urls' => [],
        'registration' => [],
      ],
    ],
  ];
}