<?php
//Add custom css to news_article nodes
function isueo_news_article_preprocess_node(&$variables) {
  $node = $variables['node'];
    //check content type
  if ($node->getType() == 'news_article') {
    $variables['#attached']['library'][] = 'isueo_news_article/isueo_news_article';
  }
}

/**
 * Implements hook_theme().
 */

function isueo_news_article_theme($existing, $type, $theme, $path)
{
   return [
      'node__news_article__teaser' => [
      'template' => 'node--news-article--teaser',
      'base hook' => 'node',
    ],
  ];
}