<?php

use Drupal\isueo_helpers\ISUEOHelpers;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_rebuild().
 */
function county_addresses_rebuild()
{
  county_addresses_handle_feed();
}

/**
 * Implements hook_cron().
 */
function county_addresses_cron()
{
  county_addresses_handle_feed();
}

function county_addresses_handle_feed()
{
  $raw = ISUEOHelpers\Files::fetch_url('https://datastore.exnet.iastate.edu/Staffdir/CountyOffices.json');
  $feed_counties = json_decode($raw, true);
  if (!$feed_counties || count($feed_counties) < 50) {
    return;
  }
  $taxonomy_counties = ISUEOHelpers\Taxonomy::get_terms('counties_in_iowa');
  $fields = [
    'field_address' => 'address_raw',
    'field_office_hours' => 'hours',
    'field_phone' => 'phone',
    'field_region' => 'region',
    'field_email' => 'email',
  ];

  foreach ($feed_counties as $county => $county_values) {
    $save = false;
    $site_name = $county_values['site_name'];
    if (array_key_exists($site_name, $taxonomy_counties)) {
      $term = Term::load($taxonomy_counties[$site_name]);
      if (!$term) {
        continue;
      }

      foreach ($fields as $taxonomy_field => $feed_field) {
        if ($term->get($taxonomy_field)->value != $county_values[$feed_field]) {
          $term->set($taxonomy_field, $county_values[$feed_field]);
          $save = true;
        }
      }

      // Handle the website
      if ($term->field_website->isEmpty() || $term->get('field_website')->first()->getURL()->toString() != $county_values['website']) {
        $term->set('field_website', ['uri' => $county_values['website'], 'title' => 'Visit ' . $site_name . ' County',]);
        $save = true;
      }

      if ($save) {
        $term->save();
        county_addresses_push_to_mydata($county_values);
      }
    }
  }
}

function county_addresses_push_to_mydata(array $drupal)
{
  // Make sure we have the salesforce module enabled
  if (!class_exists('Drupal\salesforce\SelectQuery')) {
    return;
  }

  // Fix up the site_name
  if ($drupal['site_name'] == 'Pottawattamie - East') {
    $drupal['site_name'] = 'East Pottawattamie';
  }
  if ($drupal['site_name'] == 'Pottawattamie - West') {
    $drupal['site_name'] = 'West Pottawattamie';
  }
  if ($drupal['site_name'] == "O'Brien") {
    $drupal['site_name'] = "O\'Brien";
  }

  $street = trim($drupal['address1']) . (empty($drupal['address2']) ? '' : PHP_EOL . trim($drupal['address2']));

  try {
    // Get the client service.
    $client = \Drupal::service('salesforce.client');

    // Build a SOQL query.
    $query = new Drupal\salesforce\SelectQuery('Account'); // the sObject/table name
    $query->fields = ['Id', 'Name', 'ShippingStreet', 'ShippingCity', 'ShippingState', 'ShippingStateCode', 'ShippingPostalCode'];
    $query->addCondition('Name', "'" . $drupal['site_name'] . " County Extension'", '=');
    $query->addCondition('RecordTypeId', "'012460000007ByRAAU'", '=');
    $query->limit = 1000;

    // Execute it.
    $result = $client->query($query);

    // Should only get one Record Back
    if ($result->size() != 1) {
      return;
    }

    // Get the first Record's fields
    $records = $result->records();
    $mydata = reset($records)->fields();

    // Push the updates to MyData
    $params = [
      'ShippingStreet' => $street,
      'ShippingCity' => $drupal['city'],
      'ShippingState' => 'Iowa',
      'ShippingStateCode' => $drupal['state'],
      'ShippingPostalCode' => $drupal['zip'],
    ];
    $client->objectUpdate('Account', $mydata['Id'], $params);
  } catch (Exception $ex) {
    Drupal::logger('county_addresses')->info($ex->getMessage());
  }
}
