<?php

use Drupal\isueo_helpers\ISUEOHelpers\Wrappers;

/**
 * Implements hook_install().
 */
function feature_with_large_image_install()
{
  // Add a few permissions to Content Editor role
  $permissions = [
    'access block library',
    'delete any feature_with_large_image block content',
    'edit any feature_with_large_image block content',
  ];
  Wrappers::changeRolePermissions('content_editor', $permissions, TRUE);
}
