name: 'Products'
type: module
core_version_requirement: ^10
description: 'Creates a block listing Products from the Store'
version: '10.x-1.0-dev'
package: 'ISUEO'
dependencies:
  - drupal:datetime
  - slick:slick
  - slick:slick_ui
  - slick_paragraphs:slick_paragraphs
  - slick_views:slick_views
  - blazy:blazy
  - d8modules:isueo_helpers
  - drupal:paragraphs
