<?php

use Drupal\isueo_helpers\ISUEOHelpers\Wrappers;

/**
 * Implements hook_install().
 */
function embed_block_install()
{
  // Add a few permissions to Content Editor role
  $permissions = [
    'access block library',
    'create embed_block block content',
    'delete any embed_block block content',
    'edit any embed_block block content',
    'use text format code_embed',
  ];
  Wrappers::changeRolePermissions('content_editor', $permissions, TRUE);
}
