<?php

use Drupal\node\Entity\Node;
use Drupal\isueo_helpers\ISUEOHelpers;
use Drupal\isueo_helpers\ISUEOHelpers\General;
use Drupal\isueo_helpers\ISUEOHelpers\Taxonomy;
use Drupal\isueo_helpers\ISUEOHelpers\Typesense;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_entity_delete().
 */
function plp_typesense_node_delete(Drupal\Core\Entity\EntityInterface $entity)
{
  // Only do this from the production server
  if (!ISUEOHelpers\General::is_production_server()) {
    return;
  }

  $client = plp_typesense_get_typesense_client();
  $collection_name = plp_typesense_get_typesense_collection_name();

  try {
    switch ($entity->bundle()) {
      case 'plp_program':
        $client->collections[$collection_name]->documents['plp_program:' . $entity->id()]->delete();
        break;
      case 'plp_course':
        $client->collections[$collection_name]->documents['plp_course:' . $entity->id()]->delete();
        break;
      default:
        break;
    }
  } catch (Exception $e) {
    Drupal::logger('plp_typesense')->info($e->getMessage());
  }
}

/**
* Implements hook_entity_presave().
*/
function plp_typesense_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  // Only do this from the production server
  if (!ISUEOHelpers\General::is_production_server()) {
    return;
  }

  $client = plp_typesense_get_typesense_client();
  $collection_name = plp_typesense_get_typesense_collection_name();

  try {
    switch ($entity->bundle()) {
      case 'plp_program':
        if ($entity->isPublished()) {
          plp_typesense_index_program($client, $collection_name, $entity, 'Program');
        } elseif ($entity->original->isPublished()) {
          $client->collections[$collection_name]->documents['plp_program:' . $entity->id()]->delete();
        }
        break;
      case 'plp_course':
        if ($entity->isPublished()) {
          plp_typesense_index_course($client, $collection_name, $entity, 'Course');
        } elseif (!$entity->isNew() && $entity->original->isPublished()) {
          $client->collections[$collection_name]->documents['plp_course:' . $entity->id()]->delete();
        }
        break;
      default:
        break;
    }
  } catch (Exception $e) {
    Drupal::logger('plp_typesense')->info($e->getMessage());
  }
}

// Index all nodes of a type to typesense
// Currently not used, but it could be, either in a cron command, hook_rebuild, and/or hook_cron
function plp_typesense_index_all_nodes(string $content_type='plp_program', string $type='Program')
{
  // Only do this from the production server
  if (!ISUEOHelpers\General::is_production_server()) {
    return;
  }

  $client = plp_typesense_get_typesense_client();
  $collection_name = plp_typesense_get_typesense_collection_name();
  $nids = \Drupal::entityQuery('node')->accessCheck(false)->condition('type', $content_type)->condition('status', true)->execute();
  $nodes =  Node::loadMultiple($nids);

  $client->collections[$collection_name]->documents->delete(['filter_by' => 'type:=' . $type, ]);

  foreach ($nodes as $node) {
    switch ($type) {
      case 'Program':
        plp_typesense_index_program($client, $collection_name, $node, $type);
        break;
      case 'Course':
        plp_typesense_index_course($client, $collection_name, $node, $type);
        break;
    }
  }
}

// Index a single program
function plp_typesense_index_program($client, $collection_name, $node, $type = 'Program')
{
  // Only do this from the production server
  if (!ISUEOHelpers\General::is_production_server()) {
    return;
  }

  // An empty id means it's a new program, and we don't yet have all the info we need yet
  // Don't worry, it will get saved again with the correct info almost immediately
  if (empty($node->id())) {
    return;
  }
  // Handle the easy fields
  $record = [
    'id' => 'plp_program:' . $node->id(),
    'title' => $node->getTitle(),
    'type' => $type,
    'sort_order' => intval($node->field_plp_program_sort_calc->value),
    'number_of_events' => intval($node->field_plp_program_num_events->value),
    'category_id' => intval($node->get('field_plp_program_category')->getString()),
    'smugmug_id' => $node->get('field_plp_program_smugmug')->getString(),
    'search_terms' => $node->get('field_plp_program_search_terms')->getString(),
    'event_program_ids' => unserialize($node->get('field_plp_program_event_pgm_ids')->getString()),
    'category_name' => Term::load(intval($node->get('field_plp_program_category')->getString()))->getName(),
    'body' => empty($node->get('body')->value) ? 'N/A' : $node->get('body')->value,
    'summary' => empty($node->get('body')->summary) ? 'N/A' : $node->get('body')->summary,
    'program_area' => Term::load(intval($node->get('field_plp_program_program_area')->getString()))->getName(),
    'url' => \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $node->id()),
    'children_title' => [],
    'children_body' => [],
    'topic_ids' => [],
    'topic_names' => [],
    'audiences' => [],
  ];

  // Handle Topics
  $topics = explode(', ', $node->get('field_plp_program_topics')->getString());
  foreach ($topics as $topic_id) {
    $record['topic_ids'][] = intval($topic_id);
    $record['topic_names'][] = Term::load(intval($topic_id))->getName();
  }

  // Handle Children
  $children = explode(', ', $node->get('field_plp_program_children')->getString());
  foreach ($children as $child) {
    $child_node = Node::load($child);
    if ($child_node) {
      $record['children_title'][] = $child_node->getTitle();
      $record['children_body'][] = $child_node->get('body')->getString();
    }
  }

  // Handle Audiences
  $main_audience = $node->get('field_plp_program_main_audience')->getString();
  //$record['audiences'][] = $main_audience;
  $record['audiences'][] = $main_audience . ' Programs';
  if ($main_audience == 'Youth' && str_contains($record['program_area'], '4-H')) {
    //$record['audiences'][] = '4-H Youth';
    $record['audiences'][] = 'Youth - 4-H Programs';
  } elseif ($main_audience == 'Youth') {
    //$record['audiences'][] = 'Other Youth';
    $record['audiences'][] = 'Youth - Other Programs';
  }

  $client->collections[$collection_name]->documents->upsert($record);
}

// Index a single program
function plp_typesense_index_course($client, $collection_name, $node, $type = 'Course')
{
  // Only do this from the production server
  if (!ISUEOHelpers\General::is_production_server()) {
    return;
  }

  // An empty id means it's a new program, and we don't yet have all the info we need yet
  // Don't worry, it will get saved again with the correct info almost immediately
  if (empty($node->id())) {
    return;
  }
  // Handle the easy fields
  $record = [
    'id' => 'plp_course:' . $node->id(),
    'title' => $node->getTitle(),
    'type' => $type,
    'sort_order' => 0,
    //'field_plp_program_sort_calc' => intval($node->field_plp_program_sort_calc->value),
    //'field_plp_program_num_events' => intval($node->field_plp_program_num_events->value),
    'category_id' => intval($node->get('field_plp_course_category')->getString()),
    'smugmug_id' => $node->get('field_plp_course_smugmug')->getString(),
    'search_terms' => $node->get('field_plp_course_search_terms')->getString(),
    //'field_plp_program_event_pgm_ids' => unserialize($node->get('field_plp_program_event_pgm_ids')->getString()),
    'category_name' => Term::load(intval($node->get('field_plp_course_category')->getString()))->getName(),
    'body' => empty($node->get('body')->value) ? 'N/A' : $node->get('body')->value,
    'summary' => empty($node->get('body')->summary) ? 'N/A' : $node->get('body')->summary,
    'program_area' => Term::load(intval($node->get('field_plp_course_program_area')->getString()))->getName(),
    'url' => \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $node->id()),
    'children_title' => [],
    'children_body' => [],
    'field_plp_program_topics' => [],
    'topic_names' => [],
    'audiences' => [],
  ];

  // Handle Topics
  $topics = explode(', ', $node->get('field_plp_course_topics')->getString());
  foreach ($topics as $topic_id) {
    $record['topic_ids'][] = intval($topic_id);
    $record['topic_names'][] = Term::load(intval($topic_id))->getName();
  }
/*
  // Handle Children
  $children = explode(', ', $node->get('field_plp_program_children')->getString());
  foreach ($children as $child) {
    $child_node = Node::load($child);
    if ($child_node) {
      $record['children_title'][] = $child_node->getTitle();
      $record['children_body'][] = $child_node->get('body')->getString();
    }
  }
*/

/*
  // Handle Audiences
  $main_audience = $node->get('field_plp_course_main_audience')->getString();
  //$record['audiences'][] = $main_audience;
  $record['audiences'][] = $main_audience . ' Programs';
  if ($main_audience == 'Youth' && str_contains($record['program_area'], '4-H')) {
    //$record['audiences'][] = '4-H Youth';
    $record['audiences'][] = 'Youth - 4-H Programs';
  } elseif ($main_audience == 'Youth') {
    //$record['audiences'][] = 'Other Youth';
    $record['audiences'][] = 'Youth - Other Programs';
  }
*/

$record['event_program_ids'] = ['blah'];
$record['number_of_events'] = 0;

  $client->collections[$collection_name]->documents->upsert($record);
}

function plp_typesense_get_typesense_collection_name()
{
  return 'plp_programs';
  //return 'deleteme_brian';
}

function plp_typesense_get_typesense_client()
{
  return Typesense::getClient('plp_programs');
  //return Typesense::getClient('deleteme_brian');
}
