<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\group\Entity\GroupInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK()
 */
function regcytes_preprocess_node(&$variables) {
    $variables['#attached']['library'][] = 'regcytes/regcytes';
}

/**
 * Implements hook_theme().
 */

function regcytes_theme($existing, $type, $theme, $path)
{
  return [
    'config_pages__homepage' => [
      'template' => 'config-pages--homepage',
      'base hook' => 'config_pages',
    ],
    'page__type__microsite_page__canonical' => [
      'template' => 'page--type--microsite-page--canonical',
      'base hook' => 'page',
    ],
    'isu_columns_two__config_pages_event_site_information_footer' => [
    'template' => 'isu-columns-two--config-pages-event-site-information-footer',
    'base hook' => 'config_pages',
    ],
  ];
}
