<?php

use Drupal\isueo_helpers\ISUEOHelpers\Wrappers;

/**
 * Implements hook_install().
 */
function pubs_entity_type_install()
{
  // Set up permissions, allow content editors to work with the pubs_entity content type
  $permissions = [
    'edit pubs_entity entity',
    'add pubs_entity entity',
    'delete pubs_entity entity',
    'view pubs_entity entity',
  ];
  Wrappers::changeRolePermissions('content_editor', $permissions, TRUE);
}
