<?php

use Drupal\block\Entity\Block;
use Drupal\block_content\Entity\BlockContent;
use Drupal\isueo_helpers\ISUEOHelpers\Wrappers;

/**
 * Implements hook_install().
 */
function links_block_install()
{
  // Set up permissions for content editors
  $permissions = [
    'create links_block block content',
    'delete any links_block block content',
  ];
  Wrappers::changeRolePermissions('content_editor', $permissions, TRUE);
}
